import { MapData } from "@/types/data";

// Uppdaterad data från DIGG (2025-12-14)
export const mockData: MapData = {
  municipalities: [
    { id: "m0000", name: "Alingsås", status: "connected" },
    { id: "m0001", name: "Alvesta", status: "connected" },
    { id: "m0002", name: "Aneby", status: "connected" },
    { id: "m0003", name: "Arvidsjaur", status: "started" },
    { id: "m0004", name: "Arvika", status: "connected" },
    { id: "m0005", name: "Bjurholms", status: "started" },
    { id: "m0006", name: "Bollnäs", status: "connected" },
    { id: "m0007", name: "Borgholms", status: "connected" },
    { id: "m0008", name: "Borlänge", status: "connected" },
    { id: "m0009", name: "Boxholms", status: "connected" },
    { id: "m0010", name: "Burlövs", status: "started" },
    { id: "m0011", name: "Danderyds", status: "qa" },
    { id: "m0012", name: "Eda", status: "connected" },
    { id: "m0013", name: "Eksjö", status: "connected" },
    { id: "m0014", name: "Emmaboda", status: "started" },
    { id: "m0015", name: "Enköpings", status: "started" },
    { id: "m0016", name: "Eskilstuna", status: "connected" },
    { id: "m0017", name: "Falkenbergs", status: "connected" },
    { id: "m0018", name: "Falköpings", status: "qa" },
    { id: "m0019", name: "Falu", status: "connected" },
    { id: "m0020", name: "Filipstads", status: "connected" },
    { id: "m0021", name: "Finspångs", status: "connected" },
    { id: "m0022", name: "Flens", status: "qa" },
    { id: "m0023", name: "Forshaga", status: "connected" },
    { id: "m0024", name: "Gagnefs", status: "connected" },
    { id: "m0025", name: "Gislaveds", status: "connected" },
    { id: "m0026", name: "Gnesta", status: "qa" },
    { id: "m0027", name: "Gnosjö", status: "connected" },
    { id: "m0028", name: "Gotlands", status: "connected" },
    { id: "m0029", name: "Grums", status: "connected" },
    { id: "m0030", name: "Gällivare", status: "qa" },
    { id: "m0031", name: "Gävle", status: "connected" },
    { id: "m0032", name: "Göteborgs Stad", status: "connected" },
    { id: "m0033", name: "Götene", status: "qa" },
    { id: "m0034", name: "Habo", status: "hubs" },
    { id: "m0035", name: "Hagfors", status: "connected" },
    { id: "m0036", name: "Hallsbergs", status: "connected" },
    { id: "m0037", name: "Halmstads", status: "connected" },
    { id: "m0038", name: "Hammarö", status: "connected" },
    { id: "m0039", name: "Haninge", status: "qa" },
    { id: "m0040", name: "Heby", status: "started" },
    { id: "m0041", name: "Hedemora", status: "connected" },
    { id: "m0042", name: "Helsingborgs stad", status: "connected" },
    { id: "m0043", name: "Herrljunga", status: "qa" },
    { id: "m0044", name: "Hjo", status: "qa" },
    { id: "m0045", name: "Hofors", status: "connected" },
    { id: "m0046", name: "Huddinge", status: "qa" },
    { id: "m0047", name: "Hudiksvalls", status: "hubs" },
    { id: "m0048", name: "Hultsfreds", status: "connected" },
    { id: "m0049", name: "Hylte", status: "connected" },
    { id: "m0050", name: "Håbo", status: "started" },
    { id: "m0051", name: "Hällefors", status: "connected" },
    { id: "m0052", name: "Härjedalens", status: "connected" },
    { id: "m0053", name: "Härnösands", status: "qa" },
    { id: "m0054", name: "Hässleholms", status: "qa" },
    { id: "m0055", name: "Höganäs", status: "qa" },
    { id: "m0056", name: "Högsby", status: "connected" },
    { id: "m0057", name: "Jokkmokks", status: "qa" },
    { id: "m0058", name: "Jönköpings", status: "connected" },
    { id: "m0059", name: "Kalix", status: "qa" },
    { id: "m0060", name: "Kalmar", status: "connected" },
    { id: "m0061", name: "Karlsborgs", status: "qa" },
    { id: "m0062", name: "Karlshamns", status: "qa" },
    { id: "m0063", name: "Karlskoga", status: "connected" },
    { id: "m0064", name: "Karlskrona", status: "connected" },
    { id: "m0065", name: "Karlstads", status: "connected" },
    { id: "m0066", name: "Katrineholms", status: "qa" },
    { id: "m0067", name: "Kils", status: "connected" },
    { id: "m0068", name: "Kinda", status: "connected" },
    { id: "m0069", name: "Kiruna", status: "qa" },
    { id: "m0070", name: "Klippans", status: "qa" },
    { id: "m0071", name: "Knivsta", status: "started" },
    { id: "m0072", name: "Kramfors", status: "qa" },
    { id: "m0073", name: "Kristianstads", status: "qa" },
    { id: "m0074", name: "Kristinehamns", status: "connected" },
    { id: "m0075", name: "Krokoms", status: "connected" },
    { id: "m0076", name: "Kumla", status: "connected" },
    { id: "m0077", name: "Kungsbacka", status: "connected" },
    { id: "m0078", name: "Kungälvs", status: "qa" },
    { id: "m0079", name: "Kävlinge", status: "qa" },
    { id: "m0080", name: "Köpings", status: "started" },
    { id: "m0081", name: "Laholms", status: "connected" },
    { id: "m0082", name: "Landskrona stad", status: "qa" },
    { id: "m0083", name: "Laxå", status: "connected" },
    { id: "m0084", name: "Lekebergs", status: "connected" },
    { id: "m0085", name: "Leksands", status: "connected" },
    { id: "m0086", name: "Lerums", status: "qa" },
    { id: "m0087", name: "Lidingö stad", status: "qa" },
    { id: "m0088", name: "Lidköpings", status: "qa" },
    { id: "m0089", name: "Lilla Edets", status: "qa" },
    { id: "m0090", name: "Lindesbergs", status: "connected" },
    { id: "m0091", name: "Linköpings", status: "connected" },
    { id: "m0092", name: "Ljungby", status: "connected" },
    { id: "m0093", name: "Ljusdals", status: "connected" },
    { id: "m0094", name: "Ljusnarsbergs", status: "connected" },
    { id: "m0095", name: "Lomma", status: "qa" },
    { id: "m0096", name: "Ludvika", status: "connected" },
    { id: "m0097", name: "Luleå", status: "qa" },
    { id: "m0098", name: "Lunds", status: "qa" },
    { id: "m0099", name: "Lycksele", status: "started" },
    { id: "m0100", name: "Lysekils", status: "qa" },
    { id: "m0101", name: "Malmö stad", status: "connected" },
    { id: "m0102", name: "Malung-Sälens", status: "connected" },
    { id: "m0103", name: "Malå", status: "started" },
    { id: "m0104", name: "Mariestads", status: "qa" },
    { id: "m0105", name: "Markaryds", status: "connected" },
    { id: "m0106", name: "Marks", status: "qa" },
    { id: "m0107", name: "Melleruds", status: "qa" },
    { id: "m0108", name: "Mjölby", status: "connected" },
    { id: "m0109", name: "Mora", status: "connected" },
    { id: "m0110", name: "Motala", status: "connected" },
    { id: "m0111", name: "Mullsjö", status: "connected" },
    { id: "m0112", name: "Munkedals", status: "qa" },
    { id: "m0113", name: "Munkfors", status: "connected" },
    { id: "m0114", name: "Mölndals stad", status: "qa" },
    { id: "m0115", name: "Mönsterås", status: "connected" },
    { id: "m0116", name: "Mörbylånga", status: "connected" },
    { id: "m0117", name: "Nacka", status: "qa" },
    { id: "m0118", name: "Nora", status: "connected" },
    { id: "m0119", name: "Norbergs", status: "started" },
    { id: "m0120", name: "Nordanstigs", status: "hubs" },
    { id: "m0121", name: "Nordmalings", status: "started" },
    { id: "m0122", name: "Norrköpings", status: "connected" },
    { id: "m0123", name: "Norrtälje", status: "qa" },
    { id: "m0124", name: "Norsjö", status: "started" },
    { id: "m0125", name: "Nybro", status: "connected" },
    { id: "m0126", name: "Nyköpings", status: "qa" },
    { id: "m0127", name: "Nynäshamns", status: "qa" },
    { id: "m0128", name: "Nässjö", status: "connected" },
    { id: "m0129", name: "Ockelbo", status: "connected" },
    { id: "m0130", name: "Olofströms", status: "qa" },
    { id: "m0131", name: "Orsa", status: "connected" },
    { id: "m0132", name: "Orust", status: "qa" },
    { id: "m0133", name: "Osby", status: "qa" },
    { id: "m0134", name: "Oskarshamns", status: "connected" },
    { id: "m0135", name: "Ovanåkers", status: "connected" },
    { id: "m0136", name: "Oxelösunds", status: "qa" },
    { id: "m0137", name: "Pajala", status: "qa" },
    { id: "m0138", name: "Partille", status: "qa" },
    { id: "m0139", name: "Piteå", status: "qa" },
    { id: "m0140", name: "Ragunda", status: "connected" },
    { id: "m0141", name: "Robertsfors", status: "started" },
    { id: "m0142", name: "Ronneby", status: "qa" },
    { id: "m0143", name: "Rättviks", status: "connected" },
    { id: "m0144", name: "Sala", status: "started" },
    { id: "m0145", name: "Salems", status: "qa" },
    { id: "m0146", name: "Sandvikens", status: "connected" },
    { id: "m0147", name: "Sigtuna", status: "qa" },
    { id: "m0148", name: "Simrishamns", status: "qa" },
    { id: "m0149", name: "Sjöbo", status: "qa" },
    { id: "m0150", name: "Skara", status: "qa" },
    { id: "m0151", name: "Skellefteå", status: "started" },
    { id: "m0152", name: "Skinnskattebergs", status: "started" },
    { id: "m0153", name: "Skurups", status: "qa" },
    { id: "m0154", name: "Skövde", status: "qa" },
    { id: "m0155", name: "Smedjebackens", status: "connected" },
    { id: "m0156", name: "Sollefteå", status: "qa" },
    { id: "m0157", name: "Sollentuna", status: "qa" },
    { id: "m0158", name: "Solna stad", status: "hubs" },
    { id: "m0159", name: "Sorsele", status: "started" },
    { id: "m0160", name: "Sotenäs", status: "qa" },
    { id: "m0161", name: "Staffanstorps", status: "qa" },
    { id: "m0162", name: "Stenungsunds", status: "qa" },
    { id: "m0163", name: "Stockholms stad", status: "connected" },
    { id: "m0164", name: "Storfors", status: "connected" },
    { id: "m0165", name: "Storuman", status: "started" },
    { id: "m0166", name: "Strängnäs", status: "qa" },
    { id: "m0167", name: "Strömstads", status: "qa" },
    { id: "m0168", name: "Strömsunds", status: "connected" },
    { id: "m0169", name: "Sundbybergs stad", status: "hubs" },
    { id: "m0170", name: "Sundsvalls", status: "hubs" },
    { id: "m0171", name: "Sunne", status: "connected" },
    { id: "m0172", name: "Surahammars", status: "started" },
    { id: "m0173", name: "Svalövs", status: "qa" },
    { id: "m0174", name: "Svedala", status: "qa" },
    { id: "m0175", name: "Svenljunga", status: "qa" },
    { id: "m0176", name: "Säffle", status: "connected" },
    { id: "m0177", name: "Säters", status: "connected" },
    { id: "m0178", name: "Sävsjö", status: "connected" },
    { id: "m0179", name: "Söderhamns", status: "connected" },
    { id: "m0180", name: "Söderköpings", status: "connected" },
    { id: "m0181", name: "Södertälje", status: "qa" },
    { id: "m0182", name: "Sölvesborgs", status: "qa" },
    { id: "m0183", name: "Tanums", status: "qa" },
    { id: "m0184", name: "Tibro", status: "qa" },
    { id: "m0185", name: "Tidaholms", status: "qa" },
    { id: "m0186", name: "Tierps", status: "started" },
    { id: "m0187", name: "Timrå", status: "qa" },
    { id: "m0188", name: "Tingsryds", status: "connected" },
    { id: "m0189", name: "Tjörns", status: "qa" },
    { id: "m0190", name: "Tomelilla", status: "qa" },
    { id: "m0191", name: "Torsby", status: "connected" },
    { id: "m0192", name: "Torsås", status: "connected" },
    { id: "m0193", name: "Tranemo", status: "qa" },
    { id: "m0194", name: "Tranås", status: "connected" },
    { id: "m0195", name: "Trelleborgs", status: "qa" },
    { id: "m0196", name: "Trollhättans stad", status: "hubs" },
    { id: "m0197", name: "Trosa", status: "qa" },
    { id: "m0198", name: "Tyresö", status: "qa" },
    { id: "m0199", name: "Täby", status: "qa" },
    { id: "m0200", name: "Töreboda", status: "qa" },
    { id: "m0201", name: "Uddevalla", status: "qa" },
    { id: "m0202", name: "Ulricehamns", status: "qa" },
    { id: "m0203", name: "Umeå", status: "started" },
    { id: "m0204", name: "Upplands Väsby", status: "qa" },
    { id: "m0205", name: "Upplands-Bro", status: "qa" },
    { id: "m0206", name: "Uppsala", status: "started" },
    { id: "m0207", name: "Uppvidinge", status: "connected" },
    { id: "m0208", name: "Vadstena", status: "connected" },
    { id: "m0209", name: "Vaggeryds", status: "connected" },
    { id: "m0210", name: "Valdemarsviks", status: "connected" },
    { id: "m0211", name: "Vallentuna", status: "qa" },
    { id: "m0212", name: "Vansbro", status: "connected" },
    { id: "m0213", name: "Vara", status: "qa" },
    { id: "m0214", name: "Varbergs", status: "connected" },
    { id: "m0215", name: "Vaxholms stad", status: "hubs" },
    { id: "m0216", name: "Vellinge", status: "qa" },
    { id: "m0217", name: "Vetlanda", status: "connected" },
    { id: "m0218", name: "Vilhelmina", status: "started" },
    { id: "m0219", name: "Vimmerby", status: "connected" },
    { id: "m0220", name: "Vindelns", status: "started" },
    { id: "m0221", name: "Vingåkers", status: "qa" },
    { id: "m0222", name: "Vårgårda", status: "qa" },
    { id: "m0223", name: "Vänersborgs", status: "qa" },
    { id: "m0224", name: "Vännäs", status: "hubs" },
    { id: "m0225", name: "Värmdö", status: "qa" },
    { id: "m0226", name: "Värnamo", status: "connected" },
    { id: "m0227", name: "Västerviks", status: "connected" },
    { id: "m0228", name: "Västerås stad", status: "started" },
    { id: "m0229", name: "Växjö", status: "connected" },
    { id: "m0230", name: "Ydre", status: "connected" },
    { id: "m0231", name: "Ystads", status: "qa" },
    { id: "m0232", name: "Åmåls", status: "connected" },
    { id: "m0233", name: "Ånge", status: "hubs" },
    { id: "m0234", name: "Åre", status: "connected" },
    { id: "m0235", name: "Årjängs", status: "connected" },
    { id: "m0236", name: "Åsele", status: "started" },
    { id: "m0237", name: "Åstorps", status: "qa" },
    { id: "m0238", name: "Åtvidabergs", status: "connected" },
    { id: "m0239", name: "Älmhults", status: "connected" },
    { id: "m0240", name: "Älvdalens", status: "connected" },
    { id: "m0241", name: "Älvkarleby", status: "started" },
    { id: "m0242", name: "Älvsbyns", status: "qa" },
    { id: "m0243", name: "Ängelholms", status: "qa" },
    { id: "m0244", name: "Öckerö", status: "qa" },
    { id: "m0245", name: "Ödeshögs", status: "connected" },
    { id: "m0246", name: "Örebro", status: "connected" },
    { id: "m0247", name: "Örkelljunga", status: "qa" },
    { id: "m0248", name: "Örnsköldsviks", status: "qa" },
    { id: "m0249", name: "Östersunds", status: "connected" },
    { id: "m0250", name: "Österåkers", status: "qa" },
    { id: "m0251", name: "Östhammars", status: "started" },
    { id: "m0252", name: "Östra Göinge", status: "qa" },
    { id: "m0253", name: "Överkalix", status: "qa" },
    { id: "m0254", name: "Övertorneå", status: "qa" },
  ],
  regions: [
    { id: "r00", name: "Region Dalarna", status: "started" },
    { id: "r01", name: "Region Gotland", status: "connected" },
    { id: "r02", name: "Region Gävleborg", status: "connected" },
    { id: "r03", name: "Region Halland", status: "connected" },
    { id: "r04", name: "Region Jämtland Härjedalen", status: "connected" },
    { id: "r05", name: "Region Jönköping", status: "connected" },
    { id: "r06", name: "Region Kalmar", status: "connected" },
    { id: "r07", name: "Region Norrbotten", status: "started" },
    { id: "r08", name: "Region Skåne", status: "started" },
    { id: "r09", name: "Region Stockholm", status: "connected" },
    { id: "r10", name: "Region Sörmland", status: "connected" },
    { id: "r11", name: "Region Uppsala", status: "connected" },
    { id: "r12", name: "Region Värmland", status: "connected" },
    { id: "r13", name: "Region Västerbotten", status: "connected" },
    { id: "r14", name: "Region Västernorrland", status: "qa" },
    { id: "r15", name: "Region Västmanland", status: "connected" },
    { id: "r16", name: "Region Örebro län", status: "connected" },
    { id: "r17", name: "Region Östergötland", status: "connected" },
    { id: "r18", name: "Västra Götalandsregionen", status: "connected" },
  ],
  organizations: [
    { id: "auth00", name: "Arbetsförmedlingen", type: "authority", status: "connected", location: { lat: 59.334, lng: 18.058, city: "Stockholm" } },
    { id: "auth01", name: "Försäkringskassan", type: "authority", status: "connected", location: { lat: 59.3293, lng: 18.0686, city: "Stockholm" } },
    { id: "auth02", name: "Inspektionen för vård och omsorg", type: "authority", status: "connected", location: { lat: 59.3326, lng: 18.0649, city: "Stockholm" } },
    { id: "auth03", name: "Polismyndigheten", type: "authority", status: "connected", location: { lat: 59.33, lng: 18.05, city: "Stockholm" } },
    { id: "auth04", name: "Rättsmedicinalverket", type: "authority", status: "started", location: { lat: 59.34, lng: 18.07, city: "Stockholm" } },
    { id: "auth05", name: "Skolverket", type: "authority", status: "connected", location: { lat: 59.35, lng: 18.0, city: "Solna" } },
    { id: "auth06", name: "Socialstyrelsen", type: "authority", status: "hubs", location: { lat: 59.335, lng: 18.02, city: "Stockholm" } },
    { id: "auth07", name: "Statens Institutionsstyrelse", type: "authority", status: "connected", location: { lat: 59.345, lng: 18.03, city: "Solna" } },
    { id: "other00", name: "Capio AB", type: "other", status: "connected", location: { lat: 57.7089, lng: 11.9746, city: "Göteborg" } },
    { id: "other01", name: "Folktandvården Gävleborg AB", type: "other", status: "started", location: { lat: 60.6749, lng: 17.1413, city: "Gävle" } },
    { id: "other02", name: "Hälsa Hemma Sverige AB", type: "other", status: "started", location: { lat: 57.7, lng: 11.96, city: "Göteborg" } },
    { id: "other03", name: "Höglandsförbundet", type: "other", status: "connected", location: { lat: 57.6496, lng: 14.9675, city: "Eksjö" } },
    { id: "other04", name: "Introcentrum AB", type: "other", status: "qa", location: { lat: 59.3293, lng: 18.0686, city: "Stockholm" } },
    { id: "other05", name: "Kommunalförbundet ITSAM", type: "other", status: "connected", location: { lat: 57.9945, lng: 15.656, city: "Kisa" } },
    { id: "other06", name: "Kunskapsförbundet Väst", type: "other", status: "started", location: { lat: 58.2833, lng: 12.2833, city: "Trollhättan" } },
    { id: "other07", name: "Sveriges kommuner och regioner", type: "other", status: "connected", location: { lat: 59.317, lng: 18.053, city: "Stockholm" } },
    { id: "other08", name: "Unilabs AB", type: "other", status: "started", location: { lat: 59.3293, lng: 18.0686, city: "Stockholm" } },
    { id: "new_hubs_1", name: "Cityurologen", type: "other", status: "hubs", location: { lat: 59.3326, lng: 18.0649, city: "Stockholm" } },
  ]
};
